### ISSUE TITLE
commandline script fails

### ISSUE THREAD

**Issue by andrewphilipsmith** [Living-with-machines/MapReader#64]
# How to reproduce

1. Install MapReader using either of the two methods in the README.md
2. At the shell enter the command
```bash
$ mapreader
```

# Expected outcome

A welcome note, or usage instructions or similar.

# Actual outcome

A ModuleNotFoundError:
```
Traceback (most recent call last):
  File "/Users/a.smith/anaconda3/envs/mapreader_dev/bin/mapreader", line 33, in <module>
    sys.exit(load_entry_point('mapreader', 'console_scripts', 'mapreader')())
  File "/Users/a.smith/anaconda3/envs/mapreader_dev/bin/mapreader", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/a.smith/anaconda3/envs/mapreader_dev/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/a.smith/anaconda3/envs/mapreader_dev/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mapreader.mapreader'
```

# Required Actions

- [ ] Fix entry point in `./setup.py`
- [ ] Uncomment entry point details in `./conda/meta.yaml`

**Comment by andrewphilipsmith** [comment]
This bug is also relevant to the conda package definition. (see required actions checklist).
